### ISSUE TITLE
JOSS Review 2

### ISSUE THREAD

**Issue by krystophny** [VU-BEAM-Lab/GENRE#2]
Hi @Christopher-Khan !

Finally I was able to start reviewing your work and keep you posted here.

**Comment by krystophny** [comment]
First of all, the software looks very useful and well documented. For JOSS your code is on the small (1000-2000 lines of code)  / not well known scale. I think you should include some reference to better known packages that solve GLMs with elastic-net regularisation such as  https://github.com/h2oai/h2o4gpu , and how your code stands out (e.g. it's Matlab, and there is no GPU-accelerated code for this method in Matlab yet). Please also search the net once more in case someone else did something similar already on the GPU, also in other front-end languages.

**Comment by Christopher-Khan** [comment]
Hi @krystophny! Thank you for agreeing to review this submission in order to help improve it! It's great to hear that you think the code is useful and well documented. I spent a large amount of time trying to make it user-friendly :).

In regards to your comment, I have added a reference to the H2O4GPU software package in the paper. This package and glmnet appear to be some of the most widely used packages. In terms of how this code stands out, I suppose you could technically create a MEX-interface for other packages that use GPU acceleration, but I added an extra statement to highlight how even packages that use GPUs usually just parallelize the computations for one model fit at a time. GENRE is different in that it does not parallelize the computations for one model fit. Instead, it executes many model fits in parallel, where each model fit is performed using one computational thread. Essentially, with the other GPU packages, it appears as though the main focus is using the many computational resources of the GPU for just one model fit. In addition, I tried searching for other packages that perform many model fits in parallel, but I was not able to find any particular package. Was there one that you had in mind?

Thank you again for reviewing this submission.

**Comment by krystophny** [comment]
Great, now I understand that your purpose is rather to solve many GLMs at once rather than solving a single large one. I haven't seen anything like this yet, and other GPU-enabled GLM software in R seems to be already unmaintained, so from the references this should be fine. I'll now proceed to trying out the code.

**Comment by krystophny** [comment]
One more question regarding authors. I see that Brett Byram is in the author list, but doesn't appear in the commit history on GitHub. Since he is more senior I assume that has contributed conceptual and advisory work significant for the software and you rather did the coding - is that right?

**Comment by Christopher-Khan** [comment]
Hi @krystophny. Yes. That is correct. He is my PhD advisor and contributed in the capacity that you have stated.

**Comment by krystophny** [comment]
Perfect @Christopher-Khan , thanks! If the minor points of #3 are resolved in the README, I can support publication of your work in JOSS according to https://github.com/openjournals/joss-reviews/issues/2644 .
